### ISSUE TITLE
Unhandled exception executing command 'playerlogger'

### ISSUE THREAD

**Issue by skrevt** [LuminaGames/PlayerLogger#5]
Hey :)
I got this error by typing /playerlogger getchatlogs (name)

In the mysql database everything is saved successfully but it is not available ingame

![Screenshot_9](https://user-images.githubusercontent.com/88806692/184926261-0fee353e-4c9a-45eb-86a0-8de97c6485a8.png)

**Comment by COMP-HACK** [comment]
Thank you for contacting me. I am aware of the issue. The command was not supposed to be in the plugin but I was an idiot and didn't noticed it and pushed the update. I have not developed the command yet that's why it is giving the error. The update will roll out probably in the next 2-3 days then you can use that command :)

**Comment by skrevt** [comment]
All good, thank you! :)
